### ISSUE TITLE
Bro doesn't care

### ISSUE THREAD

**Issue by Katerolon** [voidtriangle/queue-motivator#8] opened 2024-08-10 21:01 UTC
Dude, it is even more broken now. Even if I don't know the answer it counts it like it is accomplished and estimates the time based on that. Which gives a completely wrong review guestimate.

**Comment by voidtriangle** [comment] 2024-08-31 00:43
updated

**Comment by Katerolon** [comment] 2024-08-31 05:10
Thanks, but it is now going in negatives. Like if you correctly answered 2 cards out of 20 cards but you failed to answer the next 2 cards now it takes it as if you answered 0 cards and estimates the time wrong (estimated time : ∞). If you correctly answered 2 but failed to answer 3 cards now it has a net -1 cards answered so it takes negative hours to complete. Now I have to time travel to finish my queue.

**Comment by Katerolon** [comment] 2024-09-03 21:59
Bro, it isn't

**Comment by Katerolon** [comment] 2024-09-03 22:01
It isn't fixed, it is even more broken than before.

**Comment by CorgFather** [comment] 2024-09-04 22:39
@Katerolon the author is a fellow user and volunteer. He could keep the plugin completely for his own use. Please be civil. 

It sounds like you're asking for a feature request. This doesn't seem to be a bug to me. Incorrect answers are part of your review time, as are edits if you're doing them during a review. I like seeing them included because it gives me an accurate estimate of how long my review will take if I keep doing those things. The way you want it would need to be an option, or people like me would be frustrated. 

Edit: I see now that you closed and reopened it. Regardless, I think unanswered questions should count against our time. There shouldn't be negative time. If that's what happening, you may want to post pictures to document.

**Comment by Katerolon** [comment] 2024-09-05 00:47
I closed it as not planned and reopened it. You could understand it if you
were a bit attentive. It isn’t a feature request, it is a bug you would
understand if you read it. Oh and volunteering isn’t done half hearted. We
medical students when we volunteer, we do our work with diligence. That
being said I will just hire a programmer. I was thinking about deleting my
git hub acc too as I just don’t have a use for it. Sorry if it all came as
rude, but no one would tolerate my work if I didn’t put in the care for it.
So I automatically go angry when I see something is done this way, I do see
my fault though.

**Comment by CorgFather** [comment] 2024-09-07 15:03
@Katerolon It seems like by the end of your comment, your opinion changed. You could've edited yours as I did now. Insults before an apology diminish their sincerity, as does apologizing for how you're perceived rather than simply apologizing. Your volunteering is part of your education (rotations) or career advancement, so the comparison isn't fair here. 

This is the first time I've seen a user close and reopen their own issue for a response. The author hasn't instituted moderating controls, so between that and their profile, I'd say they are likely new to the platform. That's why I initially thought the author had closed it. 

I'd recommend not replying by email, as it makes you more likely to fire off a reply in anger in the moment. Maybe save it for later so you can reply in a detached manner.

Btw, you can still edit your title to be more [descriptive](https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart) it's more likely the author may interact when he has time. Right now, it just seems like venting.

You can fork the repo and make the improvements. You can then turn your issue into a Pull Request and the author can merge the code into his. Or just make the edits for yourself so it works how you like it. GitHub isn't primarily for sharing finished code with end-users, even if that's how it may seem to users. It's a [collaborative platform](https://docs.github.com/en/get-started/start-your-journey/about-github-and-git). 

Briefly, infinite time is likely caused by a denominator being 0, so look at any time calculations in the code.

If you don't have the coding ability and don't wish to learn, I'd recommend taking screenshots or video (Windows and Mac both have this built-in) to document the behavior. Debugging is a time-consuming process and things like that greatly help. I haven't seen the behavior you describe, so how am I (or the author) to know exactly what's happening without further detail? It's like if you had a patient you had to diagnose remotely based on a bit of text.

**Closed as completed** 2024-09-12 18:39 UTC
